<a href="https://colab.research.google.com/github/machinelearning147/test_repo/blob/master/pytorch_math_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!pip3 install http://download.pytorch.org/whl/cu92/torch-0.4.1-cp36-cp36m-linux_x86_64.whl

    100% |████████████████████████████████| 512.6MB 57.4MB/s 
tcmalloc: large alloc 1073750016 bytes == 0x57d9e000 @  0x7f3d6178b2a4 0x594e17 0x626104 0x51190a 0x4f5277 0x510c78 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f6070 0x510c78 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f6070 0x4f3338 0x510fb0 0x5119bd 0x4f6070


In [0]:
!pip3 install torchvision

    100% |████████████████████████████████| 61kB 3.7MB/s 
    100% |████████████████████████████████| 2.0MB 8.4MB/s 
  Found existing installation: Pillow 4.0.0
    Uninstalling Pillow-4.0.0:
      Successfully uninstalled Pillow-4.0.0


In [0]:
import torch

In [0]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [0]:
T4 = torch.zeros(2,3,2,2)

In [0]:
print(T4)

tensor([[[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]]])


In [0]:
T4[1,:,:,:]

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [0]:
T4[1,1,1,1]

tensor(0.)

In [0]:
A = [[1,2,3],[4,5,6],[7,8,9]]

In [0]:
A

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [0]:
A = torch.tensor(A)

In [0]:
A.shape

torch.Size([3, 3])

In [0]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [0]:
x

tensor([[ 1.3126,  0.0738,  0.8890,  0.4611],
        [-0.8771,  0.2997, -0.5358, -0.7181],
        [ 0.2048,  0.8965,  1.2914,  2.1380],
        [-2.3297, -1.3870,  0.9073, -1.0411]])

In [0]:
x.view(-1,2).shape

torch.Size([8, 2])

In [0]:
x.shape

torch.Size([4, 4])

In [0]:
x.unsqueeze(-1).unsqueeze(-1)

tensor([[[[ 1.3126]],

         [[ 0.0738]],

         [[ 0.8890]],

         [[ 0.4611]]],


        [[[-0.8771]],

         [[ 0.2997]],

         [[-0.5358]],

         [[-0.7181]]],


        [[[ 0.2048]],

         [[ 0.8965]],

         [[ 1.2914]],

         [[ 2.1380]]],


        [[[-2.3297]],

         [[-1.3870]],

         [[ 0.9073]],

         [[-1.0411]]]])

In [0]:
x.view(2,-1).shape

torch.Size([2, 8])

In [0]:
torch.mm(x.view(2,-1),x.view(-1,2))

tensor([[ 1.5656,  1.4114],
        [-6.5387, -5.9483]])

In [0]:
a = torch.Tensor([[1, 2, 3], [1, 2, 3]]).view(-1, 2)
b = torch.Tensor([[2, 1]]).view(2, -1)
print(a)
print(a.size())

print(b)
print(b.size())

print(torch.mm(a, b))

tensor([[1., 2.],
        [3., 1.],
        [2., 3.]])
torch.Size([3, 2])
tensor([[2.],
        [1.]])
torch.Size([2, 1])
tensor([[4.],
        [7.],
        [7.]])
